### ISSUE TITLE
Orkestra pod still crashes on initialization due to connection to Chart Museum

### ISSUE THREAD

**Issue by jonathan-innis** [Azure/orkestra#202]
- Orkestra pod still goes into `CrashLoopBackoff` on start-up. Readiness probe is not helping prevent this CrashLoopBackoff, we need to change the application logic so that the pod doesn't crash

**Comment by nitishm** [comment]
I noticed this as well - I think it;s the liveness probe. We should remove that and try, since the liveness probe is doing the same thing as readiness probe i.e. checking if chartmuseum is reachable. So it's pretty much going against what we are trying to do, which is only claim readiness when chartmuseum is up but be alive as soon as the orkestra controller is up and running/
