### ISSUE TITLE
Generate a unique prefix instead of initials when naming subcharts being pushed to the staging registry

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#262]
We need to generate a unique prefix instead of using the initials when pushing charts to the staging registry. The original reason for doing this was to prevent overwriting the subcharts of one application with the subcharts of another. 

The other option is to use the chart version in which case overwriting wouldn't cause any damage as the two charts would (ideally) be the same 

__Originally posted by @nitishm in https://github.com/Azure/orkestra/pull/247#discussion_r635433686__

**Comment by nitishm** [comment]
Let's prioritize this since we could have conflicts when two or more applications start have the same intials.

/cc @jonathan-innis

**Comment by nitishm** [comment]
Good issue for newcomers looking to contribute in Go

**Comment by mahalrs** [comment]
@nitishm I will work on this.

I think [ToInitials()](https://github.com/Azure/orkestra/blob/main/pkg/utils/helpers.go#L13) is being used to name subcharts when pushing to the staging registry. So, we want to update [reconcileApplications()](https://github.com/Azure/orkestra/blob/main/controllers/appgroup_reconciler.go#L150) to use unique prefix instead of initials. Also, I'm not sure if we also need to update [generateSubchartHelmRelease()](https://github.com/Azure/orkestra/blob/main/pkg/workflow/argo.go#L617) because it is also using ```ToInitials``` to name charts.

**Comment by nitishm** [comment]
I think both will need the up date. You can refactor the method but we will need to generate the uuid using the name of the application rather than a random number. So something like a hash of the name?!
